version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "1234:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  node_app:
    container_name: node_app
    entrypoint: .docker/entrypoint.sh
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/app

volumes:
  postgres:
