version: '3'

services:
  db:
    container_name: db
    image: postgres
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - "80:5000"
    depends_on:
      - db
    env:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/students
      - PORT=5000

  volumes:
    postgres:
