name: Deploy AWS
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - run: docker-compose down && docker-compose up -d --build 
