name: CI + Lint
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: students_test 
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/students_test"
          directory: back-end/
          file_name: .env.test

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run test
